# Generated by Django 5.1.1 on 2024-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=32)),
                ('picture', models.ImageField(upload_to='')),
                ('video', models.URLField()),
            ],
        ),
    ]
