# Generated by Django 5.1.1 on 2024-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='video',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
