# Generated by Django 5.1.1 on 2024-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.URLField(),
        ),
    ]
