# Generated by Django 5.1.1 on 2024-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_pokemon_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='video',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
