# Generated by Django 5.1.1 on 2024-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_pokemon_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
