# Generated by Django 5.1.1 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_rename_title_pokemon_name_pokemon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='favicon',
            field=models.URLField(null=True),
        ),
    ]
