# Generated by Django 5.1.1 on 2025-01-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
